/* Generated by scripts/trace-sketch.mjs from the reference sketches in scripts/reference:
 * the hand marks every page shares: arrows, underlines, a squiggle, a smile. Each sits at its own origin.
 * Do not edit by hand; change scripts/sketch-regions.mjs and run `npm run sketch`. */
import type { Drawing } from '@/components/sketch/drawing';

/** The stroke under a page title. */
export const UNDERLINE: Drawing = {
  box: [0, 0, 123, 13],
  strokes: [
    { d: 'M2.5 11.7L121.3 2.9', len: 119.1, w: 1.3, o: 0.85 },
  ],
  fills: [],
};

/** The shorter, steeper stroke under a note. */
export const UNDERSCORE: Drawing = {
  box: [0, 0, 55, 20],
  strokes: [
    { d: 'M2.5 18.5C13 14.7 23.5 11 34.2 7.7C40.5 5.9 47.1 4.7 53.3 2.5', len: 53.3, w: 1.2, o: 0.85 },
  ],
  fills: [],
};

/** A small arrow, pointing on. */
export const ARROW_RIGHT: Drawing = {
  box: [0, 0, 13, 9],
  strokes: [
    { d: 'M2.9 5.5L11.3 5.1', len: 8.4, w: 1.3, o: 0.85 },
    { d: 'M10.1 2.5C11.6 4.2 12.1 5.5 10.7 7.5', len: 5.6, w: 1.3, o: 0.9 },
  ],
  fills: [],
};

/** The longer arrow under `Code, Build, Ship`, drawn with a flick. */
export const ARROW_LONG: Drawing = {
  box: [0, 0, 16, 10],
  strokes: [
    { d: 'M2.1 7.7L13.3 4.5', len: 11.6, w: 0.9, o: 0.55 },
    { d: 'M11.3 2.1L13.5 3.7L12.5 6.9', len: 6.1, w: 1.3, o: 0.8 },
  ],
  fills: [],
};

/** The arrow beside `Scroll`. */
export const ARROW_DOWN: Drawing = {
  box: [0, 0, 12, 35],
  strokes: [
    { d: 'M5.3 2.9L5.9 33.9', len: 31, w: 1, o: 0.75 },
    { d: 'M5.9 33.3L9.9 29.5', len: 5.5, w: 1.4 },
    { d: 'M2.5 30.5L4.9 32.7', len: 3.3, w: 1.3 },
  ],
  fills: [],
};

/** The wavy line that closes a page. */
export const SQUIGGLE: Drawing = {
  box: [0, 0, 237, 16],
  strokes: [
    { d: 'M2.1 13.7C10.4 12.8 18.7 12.3 27 11C41.3 8.8 55.3 5.5 69.6 3.7C75.4 3 89.3 0.9 93.3 5.5L87.1 10.7C90 13 96.6 11.3 100.1 10.7C111.2 9.1 122.4 8.8 133.5 7.7', len: 147.6, w: 1.3, o: 0.45 },
    { d: 'M154.9 7.7C174.1 7.7 193.2 6.7 212.3 4.5C217.8 3.9 223.5 3.6 228.9 2.5', len: 74.2, w: 1.3, o: 0.35 },
    { d: 'M232.7 2.3L234.7 2.1', len: 2, w: 0.8, o: 0.35 },
  ],
  fills: [],
};

/** The smile after `Thanks for stopping by!`. */
export const SMILE: Drawing = {
  box: [0, 0, 14, 14],
  strokes: [
    { d: 'M2.5 11.1C6.9 13.9 10.8 12.4 11.7 7.1', len: 12.5, w: 1.4, o: 0.95 },
    { d: 'M2.5 4.9L3.5 6.5', len: 1.9, w: 1.4, o: 0.95 },
    { d: 'M6.5 2.9L7.5 4.3', len: 1.7, w: 1.4, o: 0.85 },
  ],
  fills: [],
};
