/* Generated by scripts/trace-sketch.mjs from the reference sketches in scripts/reference:
 * the hand marks every page shares: arrows, underlines, a squiggle, a smile. Each sits at its own origin.
 * Do not edit by hand; change scripts/sketch-regions.mjs and run `npm run sketch`. */
import type { Drawing } from '@/components/sketch/drawing';

/** The stroke under a page title. */
export const UNDERLINE: Drawing = {
  box: [0, 0, 123, 13],
  strokes: [
    { d: 'M121.3 2.9L2.5 11.7', len: 119.1, w: 1.3, o: 0.85 },
  ],
  fills: [],
};

/** The shorter, steeper stroke under a note. */
export const UNDERSCORE: Drawing = {
  box: [0, 0, 55, 20],
  strokes: [
    { d: 'M53.3 2.5C53.3 2.5 38.3 6.2 30.9 8.5C22.4 11.2 2.5 18.5 2.5 18.5', len: 53.3, w: 1.2, o: 0.85 },
  ],
  fills: [],
};

/** A small arrow, pointing on. */
export const ARROW_RIGHT: Drawing = {
  box: [0, 0, 13, 9],
  strokes: [
    { d: 'M2.9 5.5L11.3 5.1', len: 8.4, w: 1.3, o: 0.85 },
    { d: 'M10.1 2.5C10.1 2.5 11.7 4.2 11.9 4.9C12.1 5.5 11.7 6.5 11.5 6.9C11.4 7.2 10.7 7.5 10.7 7.5', len: 6, w: 1.3, o: 0.9 },
  ],
  fills: [],
};

/** The longer arrow under `Code, Build, Ship`, drawn with a flick. */
export const ARROW_LONG: Drawing = {
  box: [0, 0, 16, 10],
  strokes: [
    { d: 'M11.3 2.1C11.3 2.1 12.5 2.4 12.9 2.7C13.3 3 13.7 4.1 13.7 4.1L2.1 7.7', len: 15.5, w: 1, o: 0.6 },
    { d: 'M12.5 6.9L13.5 4.5', len: 2.6, w: 1.4, o: 0.8 },
  ],
  fills: [],
};

/** The arrow beside `Scroll`. */
export const ARROW_DOWN: Drawing = {
  box: [0, 0, 12, 35],
  strokes: [
    { d: 'M5.3 2.9C5.3 2.9 5.7 27.3 5.7 32.3C5.7 32.6 5.1 32.9 5.1 32.9C5.1 32.9 4.2 32.6 3.9 32.3C3.5 31.9 2.5 30.5 2.5 30.5', len: 33.9, w: 1, o: 0.75 },
    { d: 'M9.9 29.5L5.9 33.9', len: 5.9, w: 1.4 },
  ],
  fills: [],
};

/** The wavy line that closes a page. */
export const SQUIGGLE: Drawing = {
  box: [0, 0, 237, 16],
  strokes: [
    { d: 'M133.5 7.7C133.5 7.7 124.8 7.9 120.5 8.3C113.1 9 94.6 11.4 89.1 11.9C88.6 11.9 88 11.8 87.7 11.5C87.4 11.2 87.1 10.3 87.1 10.3C87.1 10.3 92.3 7 93.3 6.1C93.6 5.9 93.5 5.4 93.3 5.1C93.1 4.7 92.5 4.2 91.9 3.9C91.1 3.5 89.8 3 88.7 2.9C85.9 2.7 79.8 2.6 75.3 2.9C70.1 3.3 63.4 4.3 57.5 5.3C49.5 6.7 35.2 9.8 27.5 11.1C22.1 12 15.5 12.9 11.3 13.3C8.2 13.6 2.1 13.7 2.1 13.7', len: 148.6, w: 1.3, o: 0.45 },
    { d: 'M228.9 2.5C228.9 2.5 215.3 4.4 208.5 5.1C201.1 5.9 192.5 6.7 184.5 7.1C175.6 7.5 154.9 7.7 154.9 7.7', len: 74.3, w: 1.3, o: 0.35 },
    { d: 'M234.7 2.1L232.7 2.3', len: 2, w: 0.8, o: 0.35 },
  ],
  fills: [],
};

/** The smile after `Thanks for stopping by!`. */
export const SMILE: Drawing = {
  box: [0, 0, 14, 14],
  strokes: [
    { d: 'M11.7 7.1C11.7 7.1 11.7 8.9 11.3 9.7C10.9 10.6 10 11.8 9.1 12.3C8.2 12.8 7 13.1 5.9 12.9C4.8 12.7 2.5 11.1 2.5 11.1', len: 13.1, w: 1.4, o: 0.95 },
    { d: 'M2.5 4.9L3.5 6.5', len: 1.9, w: 1.4, o: 0.95 },
    { d: 'M6.5 2.9L7.5 4.3', len: 1.7, w: 1.4, o: 0.85 },
  ],
  fills: [],
};
