/* Generated by scripts/trace-sketch.mjs from the reference sketches in scripts/reference:
 * the Contact page. Coordinates are the collage sheet's own.
 * Do not edit by hand; change scripts/sketch-regions.mjs and run `npm run sketch`. */
import type { Drawing } from '@/components/sketch/drawing';

/** The dashes the paper plane leaves behind it, from where it set off to where it is. */
export const TRAIL: Drawing = {
  box: [1089, 843, 99, 91],
  strokes: [
    { d: 'M1185.5 931.3L1181.5 932.3', len: 4.1, w: 1 },
    { d: 'M1174.5 932.5L1171.9 932.5', len: 2.6, w: 1 },
    { d: 'M1164.7 931.5L1162.5 931.1', len: 2.2, w: 1.1 },
    { d: 'M1155.9 928.7L1153.7 927.5', len: 2.5, w: 1.3 },
    { d: 'M1148.7 924.9L1146.9 923.3', len: 2.4, w: 1.4 },
    { d: 'M1142.5 919.1L1140.7 917.1', len: 2.7, w: 1.4 },
    { d: 'M1138.3 912.5L1136.3 909.1', len: 3.9, w: 1.2 },
    { d: 'M1133.9 909.5L1136.3 908.9L1136.5 906.3', len: 5.1, w: 1.2 },
    { d: 'M1141.9 907.3L1144.9 905.3', len: 3.6, w: 1.4 },
    { d: 'M1148.5 902.1L1150.7 899.7', len: 3.3, w: 1.2 },
    { d: 'M1153.3 895.1L1154.3 892.7', len: 2.6, w: 1.3 },
    { d: 'M1153.7 887.1L1151.7 885.3', len: 2.7, w: 1.2 },
    { d: 'M1145.7 885.3L1143.3 886.7', len: 2.8, w: 1.2 },
    { d: 'M1139.5 890.7L1137.7 893.3', len: 3.2, w: 1.2 },
    { d: 'M1136.5 898.5L1136.3 900.1', len: 1.6, w: 1.3 },
    { d: 'M1127.5 909.7L1124.9 909.3', len: 2.6, w: 1.3 },
    { d: 'M1118.9 908.3L1116.5 907.1', len: 2.7, w: 1.3 },
    { d: 'M1110.5 904.3L1108.3 902.5', len: 2.8, w: 1.4 },
    { d: 'M1103.5 899.1L1101.3 897.1', len: 3, w: 1.2 },
    { d: 'M1097.5 892.1L1095.5 889.5', len: 3.3, w: 1.3 },
    { d: 'M1092.7 883.3L1092.3 881.7', len: 1.6, w: 1.1 },
    { d: 'M1091.3 875.1L1091.3 873.5', len: 1.6, w: 1.3 },
    { d: 'M1091.9 866.9L1093.1 864.3', len: 2.9, w: 1.2 },
    { d: 'M1103.9 847.5L1105.7 845.9', len: 2.4, w: 1.1 },
  ],
  fills: [],
};

/** The paper plane itself. */
export const PAPER_PLANE: Drawing = {
  box: [1101, 821, 33, 24],
  strokes: [
    { d: 'M1109.9 842.9C1110.4 841 1110.8 839.8 1112.3 838.5L1119.7 842.7L1131.9 823.3', len: 36.5, w: 1.5 },
    { d: 'M1103.5 833.1L1129.3 823.7', len: 27.5, w: 1.5 },
    { d: 'M1110.1 840.1C1109.6 838.9 1109.2 838 1110 836.7C1111.4 834.2 1121.4 829.7 1124.3 828.1', len: 20.4, w: 1.4 },
    { d: 'M1112.9 838.1L1119.5 832.3', len: 8.8, w: 1.2 },
    { d: 'M1104.3 833.1C1105.8 834.7 1107.6 835.4 1109.7 836.1', len: 6.3, w: 1.4 },
    { d: 'M1110.5 842.1C1112.2 842 1113.2 841.7 1114.1 840.3', len: 4.2, w: 1.4 },
  ],
  fills: [],
};
